create extension if not exists pgcrypto;

do $$ begin
  create type public.user_role as enum ('user', 'admin');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.project_status as enum ('draft', 'published');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.section_type as enum ('welcome', 'story', 'gallery', 'wishes', 'closing');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.contribution_status as enum ('pending', 'approved', 'rejected');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.notification_type as enum ('new_contribution');
exception when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  name text,
  role public.user_role not null default 'user',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  creator_id uuid not null references public.profiles(id) on delete cascade,
  celebrant_name text not null,
  birthday_date timestamptz not null,
  cover_photo_url text,
  welcome_message text,
  spotify_url text,
  status public.project_status not null default 'draft',
  public_url text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sections (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  type public.section_type not null,
  display_order integer not null,
  content text,
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contributions (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  contributor_name text not null,
  message text not null,
  profile_photo_url text,
  photo_with_celebrant_url text,
  status public.contribution_status not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  creator_id uuid not null references public.profiles(id) on delete cascade,
  contribution_id bigint references public.contributions(id) on delete cascade,
  type public.notification_type not null,
  content text not null,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists projects_creator_id_idx on public.projects(creator_id);
create index if not exists projects_public_url_idx on public.projects(public_url);
create index if not exists sections_project_id_order_idx on public.sections(project_id, display_order);
create index if not exists contributions_project_id_idx on public.contributions(project_id);
create index if not exists notifications_creator_id_idx on public.notifications(creator_id);

alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.sections enable row level security;
alter table public.contributions enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
  for select using (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "projects_select_own_or_published" on public.projects;
create policy "projects_select_own_or_published" on public.projects
  for select using (auth.uid() = creator_id or status = 'published');

drop policy if exists "projects_insert_own" on public.projects;
create policy "projects_insert_own" on public.projects
  for insert with check (auth.uid() = creator_id);

drop policy if exists "projects_update_own" on public.projects;
create policy "projects_update_own" on public.projects
  for update using (auth.uid() = creator_id) with check (auth.uid() = creator_id);

drop policy if exists "projects_delete_own" on public.projects;
create policy "projects_delete_own" on public.projects
  for delete using (auth.uid() = creator_id);

drop policy if exists "sections_select_visible_project" on public.sections;
create policy "sections_select_visible_project" on public.sections
  for select using (
    exists (
      select 1 from public.projects p
      where p.id = sections.project_id
      and (p.creator_id = auth.uid() or p.status = 'published')
    )
  );

drop policy if exists "sections_write_own_project" on public.sections;
create policy "sections_write_own_project" on public.sections
  for all using (
    exists (
      select 1 from public.projects p
      where p.id = sections.project_id
      and p.creator_id = auth.uid()
    )
  ) with check (
    exists (
      select 1 from public.projects p
      where p.id = sections.project_id
      and p.creator_id = auth.uid()
    )
  );

drop policy if exists "contributions_select_own_project_or_approved" on public.contributions;
create policy "contributions_select_own_project_or_approved" on public.contributions
  for select using (
    status = 'approved'
    or exists (
      select 1 from public.projects p
      where p.id = contributions.project_id
      and p.creator_id = auth.uid()
    )
  );

drop policy if exists "contributions_insert_public" on public.contributions;
create policy "contributions_insert_public" on public.contributions
  for insert with check (
    exists (
      select 1 from public.projects p
      where p.id = contributions.project_id
      and p.public_url is not null
    )
  );

drop policy if exists "contributions_update_own_project" on public.contributions;
create policy "contributions_update_own_project" on public.contributions
  for update using (
    exists (
      select 1 from public.projects p
      where p.id = contributions.project_id
      and p.creator_id = auth.uid()
    )
  ) with check (
    exists (
      select 1 from public.projects p
      where p.id = contributions.project_id
      and p.creator_id = auth.uid()
    )
  );

drop policy if exists "contributions_delete_own_project" on public.contributions;
create policy "contributions_delete_own_project" on public.contributions
  for delete using (
    exists (
      select 1 from public.projects p
      where p.id = contributions.project_id
      and p.creator_id = auth.uid()
    )
  );

drop policy if exists "notifications_select_own" on public.notifications;
create policy "notifications_select_own" on public.notifications
  for select using (auth.uid() = creator_id);

drop policy if exists "notifications_update_own" on public.notifications;
create policy "notifications_update_own" on public.notifications
  for update using (auth.uid() = creator_id) with check (auth.uid() = creator_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'birthday-keepsake',
  'birthday-keepsake',
  true,
  52428800,
  array['image/png', 'image/jpeg', 'image/webp', 'image/gif', 'application/octet-stream']
)
on conflict (id) do update set public = excluded.public;

drop policy if exists "storage_public_read" on storage.objects;
create policy "storage_public_read" on storage.objects
  for select using (bucket_id = 'birthday-keepsake');

drop policy if exists "storage_authenticated_write" on storage.objects;
create policy "storage_authenticated_write" on storage.objects
  for insert with check (bucket_id = 'birthday-keepsake');

drop policy if exists "storage_authenticated_update" on storage.objects;
create policy "storage_authenticated_update" on storage.objects
  for update using (bucket_id = 'birthday-keepsake') with check (bucket_id = 'birthday-keepsake');
